<font color="blue">

### Data Science Academy

### Big Data Real-Time Analytics com Python e Spark

### Capítulo 2</font>

### Computação com Numpy

In [5]:
#Importando o módulo numpy
import numpy as np

#### Criando Estruturas de Dados NumPy

In [9]:
# Criando array unidimenssional
array1 = np.array([10,20,30,40])

#Criando array bi-dmensional
array2 = np.array([[100,83,15], [42,78,0]])

In [10]:
array1

array([10, 20, 30, 40])

In [11]:
array2

array([[100,  83,  15],
       [ 42,  78,   0]])

In [12]:
#Verificando o formato (shape) do array
array1.shape

(4,)

In [13]:
#Verificando o formato (shape) do array
array2.shape

(2, 3)

In [17]:
#Verificando o numero de dimensões
array2.ndim

2

### Em Python TUDO é objeto, com métodos e atributos

#### Método - realiza ação no objeto

#### Atributo - característica do objeto

In [18]:
# Método
array2.max()

100

In [19]:
# Atributo
array2.ndim

2

### Criando estruturas de dados com arange

In [29]:
array3 = np.arange(15)

In [30]:
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
#Usando start/end (exclusivo)
array = np.arange(0,15,5)

In [27]:
array

array([ 0,  5, 10])

### Criando estruturas de dados com linspace

In [33]:
#Arguementos (start, end, number of elements)
array4 = np.linspace(0,3,4)
array4 

array([0., 1., 2., 3.])

### Criando estrutura de dados com outras funções

#### numpy.zeros

In [34]:
# Array 10x8 de zeros
array6 = np.zeros((10,8)); array6

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

#### numpy.ones

In [36]:
# Array 2x3x2 dee 1's
array7 = np.ones((2,3,2)); array7

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

##### numpy.eye

In [37]:
#Produz um Identitiy Matrix
array8 = np.eye(3); array8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### numpy.diag

In [39]:
# Matriz diagonal
array9 = np.diag((2,3,4,5)); array9

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

##### numpy.random.rand

In [42]:
# A função rand(n) produz um a sequencia de numeros uniformemente distribuidos com range de 0 a n
np.random.seed(100) #Set seed
array10 = np.random.rand(5); array10

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [44]:
# A função randn(n) produz uma sequência de números com distribuição normal ( Gaussion)

array11 = np.random.randn(5); array11

array([ 0.35467445, -0.78606433, -0.2318722 ,  0.20797568,  0.93580797])

##### numpy.empty

In [56]:
array12 = np.empty((3,2))

In [57]:
array12

array([[8.90077926e-308, 1.00132568e-307],
       [9.45697133e-308, 1.08223599e-312],
       [2.11394409e-307, 4.00540117e-307]])

##### numpy.tile

In [58]:
np.array([[9,4],[3,7]])

array([[9, 4],
       [3, 7]])

In [59]:
np.tile(np.array([[9,4],[3,7]]), 4)

array([[9, 4, 9, 4, 9, 4, 9, 4],
       [3, 7, 3, 7, 3, 7, 3, 7]])

In [60]:
np.tile(np.array([[9,4], [3,7]]), (2,2))

array([[9, 4, 9, 4],
       [3, 7, 3, 7],
       [9, 4, 9, 4],
       [3, 7, 3, 7]])

### Tipos de Dados Numpy

In [61]:
array13 = np.array([8,-3,5,9], dtype="float")

In [62]:
array13

array([ 8., -3.,  5.,  9.])

In [63]:
array13.dtype

dtype('float64')

In [65]:
array14 = np.array([2,4,6,8])

In [66]:
array14

array([2, 4, 6, 8])

In [67]:
array14.dtype

dtype('int32')

In [68]:
array15 = np.array([2.0, 4, 6, 8])

In [69]:
array15

array([2., 4., 6., 8.])

In [71]:
array15.dtype

dtype('float64')

In [72]:
array16 = np.array(['Análise', 'de', 'Dados', 'comn Python'])

In [73]:
array16

array(['Análise', 'de', 'Dados', 'comn Python'], dtype='<U11')

In [74]:
array16.dtype

dtype('<U11')

In [75]:
array16.shape

(4,)

In [76]:
array17 = np.array([True, False, True])

In [77]:
array17

array([ True, False,  True])

In [79]:
array17.dtype

dtype('bool')

In [80]:
array18 = np.array([7,-3,5.24])

In [81]:
array18

array([ 7.  , -3.  ,  5.24])

In [83]:
array18.dtype

dtype('float64')

In [84]:
array18.astype(int)

array([ 7, -3,  5])

In [85]:
array18.astype(str)

array(['7.0', '-3.0', '5.24'], dtype='<U32')

### Operações com Arrays

In [86]:
# Array começando por 0, com 30 elementos e multiplicado por 5
array19 = np.arange(0,30) * 5

In [87]:
array19

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145])

In [89]:
array19 = np.arange(0,30)

In [90]:
array19

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [98]:
#Elevando uma array a potência
array20 = np.arange(5) ** 4

In [99]:
array20

array([  0,   1,  16,  81, 256], dtype=int32)

In [100]:
# Somando um número a cada elemento do array
array21 = np.arange(0,30) + 1

In [101]:
array21

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

##### Operaçães entre os arrays

In [104]:
array22 = np.arange(0,30,3) + 3
array23 = np.arange(1,11)

In [105]:
array22

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [106]:
array23

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
#Subtração
array22 - array23

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [108]:
# Adição
array22 + array23

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [109]:
#Divisão
array22 / array23

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [110]:
#Multiplicação
array22 * array23

array([  3,  12,  27,  48,  75, 108, 147, 192, 243, 300])

In [111]:
#Podemos ainda comparar arrays
array22 > array23

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [112]:
arr1 = np.array([True, False, True, False])
arr2 = np.array([False, False, True, False])
np.logical_and(arr1, arr2)

array([False, False,  True, False])

#### Podemos criar arrays com Python, sem usar o módulo NumPy é muito mais rápido


In [119]:
array_numpy = np.arange(1000)
%timeit array_numpy ** 4

38.8 µs ± 8.19 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [120]:
array_python = range(1000)
%timeit [array_python[i] ** 4 for i in array_python]

5.33 ms ± 936 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### That's it