<font color="blue">

### Data Science Academy

### Big Data Real-Time Analytics com Python e Spark

### Capítulo 2</font>

### Transposição e Reshaping de Arrays

In [1]:
#Importing o módulo Numpy
import numpy as np

In [3]:
array1 = np.array([[65,23,19], [41,87,10]])

In [4]:
array1

array([[65, 23, 19],
       [41, 87, 10]])

In [7]:
#Fazendo o pivô dos dados, trabformando linha em coluna e vice-versa
array1.T

array([[65, 41],
       [23, 87],
       [19, 10]])

In [8]:
np.transpose(array1)

array([[65, 41],
       [23, 87],
       [19, 10]])

### Broadcasting

In [9]:
array2 = np.array([[33,34,35]])

In [12]:
array2.T

array([[33],
       [34],
       [35]])

In [13]:
array2.T + array2

array([[66, 67, 68],
       [67, 68, 69],
       [68, 69, 70]])

### Tranformando Matrizes em Vetores

In [14]:
array3 = np.array([np.arange(1,6), np.arange(10,15)])

In [15]:
array3

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [16]:
#Conversão de uma matriz em vetor
array3.ravel()

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [18]:
array3.T.ravel()

array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14])

### Operadores Lógicos

In [26]:
#Gerando uma matriz 4x4 com valores randomicos de 1 a 10
np.random.seed(100)
array4 = np.random.randint(1,10,size=(4,4))

In [27]:
array4

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3],
       [2, 1, 9, 5]])

In [28]:
# Any é um método que me retorna qualquer coisa dentro da matriz baseao em uma regra
# A regra nesse caso são valores divisiveis por 7, onde o resto da divisião é igua a zero
# O resultado é um valor boolean.
np.any((array4 % 7) == 0)

False

In [29]:
# All é uma função que verifica a regra para todos os elemento e retorna um valor boolean.
np.all(array4 < 11)

True

### Reshaping

In [30]:
array5 = np.arange(1,16)

In [31]:
array5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [33]:
#Convertendo um vetor numa matriz
array5.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

### Ordenando um Array

In [34]:
array7 = np.array([[3,2],[10,-1]])

In [35]:
array7

array([[ 3,  2],
       [10, -1]])

In [38]:
#Ordenando por linhas
array7.sort(axis = 1)

In [39]:
array7

array([[ 2,  3],
       [-1, 10]])

In [42]:
array8 = np.array([[3,2],[10,-1]])

In [43]:
array8

array([[ 3,  2],
       [10, -1]])

In [44]:
#Ordenanando por colunas
array8.sort(axis=0)

In [45]:
array8

array([[ 3, -1],
       [10,  2]])

### Fim