### Numpy

Numpy oferece sequências de elementos que são mais eficientes que sequências padrões em Python

In [1]:
import sys
import numpy as np 
print(sys.version)
np.__version__

3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]


'1.18.1'

### Concatenando Arrays

In [2]:
array1 = np.ones(4)

In [5]:
array2 = np.arange(15)

In [7]:
array_conc = np.concatenate([array1, array2])

In [8]:
array_conc

array([ 1.,  1.,  1.,  1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,
        9., 10., 11., 12., 13., 14.])

### Join Arrays

In [10]:
a = np.ones((3,3))
b = np.zeros((3,3))

In [11]:
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
?np.vstack

In [14]:
?np.hstack

In [19]:
# Primeiro preenche as linhas 
np.vstack((a,b))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
#Primeiro preenche as colunas
np.hstack((a,b))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [21]:
# Joining arrays
a = np.array([0,1,2])
b = np.array([3,4,5])
c = np.array([6,7,8])

In [22]:
?np.column_stack

In [23]:
?np.row_stack

In [25]:
np.column_stack((a,b,c))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [26]:
np.row_stack((a,b,c))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Split Arrays

In [27]:
array3 = np.arange(16).reshape((4,4)); array3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
?np.hsplit

In [31]:
?np.vsplit

In [28]:
[array3_p1, array3_p2] = np.hsplit(array3, 2)

In [29]:
array3_p1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [33]:
array3_p2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [35]:
[array3_p3, array3_p4] = np.vsplit(array3,2)

In [38]:
array3_p3

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [39]:
array3_p4

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Gravando e Carregando Dados com Numpy

In [40]:
dados = array3

In [41]:
np.save('dados_saved_v1', dados )

In [42]:
loaded_data = np.load("dados_saved_v1.npy")

In [43]:
loaded_data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Fim