### Numpy

#### Arrays Numpy - objetos multidimensionais com N dimensões

#### Matrizes Numpy - objetos com 2 dimensões

A principal vantagem de utilizar matrizes com Numpy, é que este tipo de objeto possui convinientes notações para multiplicação de matrizes. Array e Matrizes Numpy possuem o atributo .T para retornar a transposta da matriz, enquanto objetos do tipo matrizes possuem  adicionalmente os atributos .I (Inversa) e .H (Transposta Conjugada).

Existem diferenças em operaçõe de álgebra linear entre arrays e matrizes.  </br>

Muitas funções Numpy retornam arrays e não matrizes como objeto resultante.

In [4]:
import sys
import numpy as np
print(sys.version)
np.__version__

3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]


'1.18.1'

### Criando Matrizes

In [18]:
mat1 = np.matrix('1,2,3;4,5,6'); print(mat1)

[[1 2 3]
 [4 5 6]]


In [7]:
type(mat1)

numpy.matrix

In [9]:
mat2 = np.matrix([[1,2,3], [4,5,6]]); print(mat2)

[[1 2 3]
 [4 5 6]]


In [14]:
mat3 = np.matrix([[0,10,0,0,0], [0,0,20,0,0],[0,0,0,30,0], [0,0,0,0,40], [0,0,0,0,0]])
print(mat3)

[[ 0 10  0  0  0]
 [ 0  0 20  0  0]
 [ 0  0  0 30  0]
 [ 0  0  0  0 40]
 [ 0  0  0  0  0]]


In [19]:
type(mat3)

numpy.matrix

In [16]:
mat3[2,3]

30

### Operações Matemáticas com Arrays e Matrizes

In [21]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [22]:
type(a)

numpy.ndarray

In [23]:
a * a

array([[ 1,  4],
       [ 9, 16]])

In [30]:
A = np.mat(a); A

matrix([[1, 2],
        [3, 4]])

In [32]:
type(A)

numpy.matrix

In [31]:
A * A

matrix([[ 7, 10],
        [15, 22]])

In [34]:
np.dot(a, a)

array([[ 7, 10],
       [15, 22]])

In [37]:
#Convertendo um Array para MAtriz
mat5 = np.asmatrix(a)

In [38]:
mat5

matrix([[1, 2],
        [3, 4]])

In [39]:
mat5 * mat5

matrix([[ 7, 10],
        [15, 22]])

In [41]:
#Convertendo uma matriz para um Array
array2 = np.asarray(mat5)

In [42]:
array2

array([[1, 2],
       [3, 4]])

In [43]:
array2 * array2

array([[ 1,  4],
       [ 9, 16]])

### Fim